name:                HaskellMySQL
version:             0.1.0.0
github:              "jtnuttall/HaskellMySQL"
license:             BSD3
author:              "Jeremy Nuttall"
maintainer:          "jtnuttal@usc.edu"
copyright:           "(c) 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jtnuttall/HaskellMySQL#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 1.0
- optparse-applicative == 0.14.2.0
- text >= 1.2 && < 1.3
- aeson >= 1.2 && < 1.4
- mysql-simple == 0.4.5

library:
  source-dirs: src

executables:
  HaskellMySQL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellMySQL

tests:
  HaskellMySQL-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellMySQL
